#!/usr/bin/env uv run --script
# /// script
# requires-python = ">=3.9"
# dependencies = [
#     "pyyaml>=6.0.3",
# ]
# ///
"""Fetch tmux-nerd-font-window-name icon map and generate tab_bar.py for kitty."""

import urllib.request
import yaml
from pathlib import Path

URL = 'https://raw.githubusercontent.com/joshmedeski/tmux-nerd-font-window-name/main/bin/defaults.yml'
OUT = Path(__file__).parent / 'tab_bar.py'

# Local overrides — survives regeneration
EXTRA_ICONS = {
  'gh': '',
  'gh-dash': '',
  'gh-enhance': '',
  'gt': '󰊢',
  'nvim': '',
  'mprocs': '',
  'yazi': '󰙅',
  'man': '',
  'devbox': '',
  'openapi-tui': '󱂛',
  'iris': '',
}

TEMPLATE = '''\
# Auto-generated by generate_tab_bar.py — do not edit manually
# Process name -> Nerd Font icon mapping
# Source: {url}

EXE_ICON = {icon_dict}

SHELLS = {{'zsh', 'bash', '-fish', 'sh', 'dash', 'nu', 'nushell', 'tcsh'}}
SHELL_ICON = ''       # ›
DEFAULT_ICON = '\\U000F0174'  # 󰅴


def draw_title(data):
    session_name = ""
    index = data['index']
    if index == 1:
        session_name = f'{{data['session_name']}} ▸ '
    tab = data['tab']
    title = data['title']
    exe = tab.active_exe

    if exe in SHELLS:
        icon = SHELL_ICON
    else:
        icon = EXE_ICON.get(exe, DEFAULT_ICON)

    label = title if len(title) < 15 else (exe.split()[0] if exe else title)
    label = label.replace('\\n', '').strip()

    return f'{{session_name}}{{index}} {{icon}} {{label}}'
'''


def icon_to_escape(ch):
    cp = ord(ch)
    if cp > 0xFFFF:
        return f'\\U{cp:08X}'
    if cp > 0x7E:
        return f'\\u{cp:04X}'
    return ch


def main():
    print(f'Fetching {URL}')
    with urllib.request.urlopen(URL) as r:
        data = yaml.safe_load(r.read())

    icons = data['icons']
    icons.update(EXTRA_ICONS)
    lines = []
    for exe in sorted(icons):
        esc = icon_to_escape(icons[exe])
        lines.append(f"    {exe!r}: '{esc}',")

    icon_dict = '{\n' + '\n'.join(lines) + '\n}'
    code = TEMPLATE.format(url=URL, icon_dict=icon_dict)

    OUT.write_text(code)
    print(f'Wrote {OUT} ({len(icons)} icons)')


if __name__ == '__main__':
    main()
