require("indent_blankline").setup({})
require("nvim-web-devicons").setup({ default = true })
require("gitsigns").setup({})
require("trouble").setup({})
require("dlvhdr.nvim-tree")
require("dlvhdr.lualine")
require("dlvhdr.telescope")
require("dlvhdr.lsp")
require("dlvhdr.treesitter")
require("dlvhdr.autopairs")
require("dlvhdr.project")
require("dlvhdr.dap")
require("dlvhdr.terminal")
require("dlvhdr.dashboard")
require("dlvhdr.colors")
require("dlvhdr.auto-session")
