# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marker

# : Flavor {{{

[flavor]
use = ""

# : }}}

# : Manager {{{

[manager]
cwd = { fg = "cyan" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "yellow", bold = true, italic = true, underline = true }
find_position = { fg = "magenta", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "lightgreen",  bg = "lightgreen" }
marker_cut      = { fg = "lightred",    bg = "lightred" }
marker_marked   = { fg = "lightyellow", bg = "lightyellow" }
marker_selected = { fg = "lightblue",   bg = "lightblue" }

# Tab
tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

# Count
count_copied   = { fg = "white", bg = "green" }
count_cut      = { fg = "white", bg = "red" }
count_selected = { fg = "white", bg = "blue" }

# Border
border_symbol = "│"
border_style  = { fg = "#1f2335" }

# Highlighting
syntect_theme = ""

# : }}}


# : Status {{{

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#1f2335", bg = "#1f2335" }

# Mode
mode_normal = { bg = "blue", fg = "black", bold = true }
mode_select = { bg = "red", fg="black", bold = true }
mode_unset  = { bg = "red", fg="black", bold = true }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "blue", bg = "black" }
progress_error  = { fg = "red", bg = "black" }

# Permissions
permissions_t = { fg = "green" }
permissions_r = { fg = "yellow" }
permissions_w = { fg = "red" }
permissions_x = { fg = "cyan" }
permissions_s = { fg = "darkgray" }

# : }}}


# : Select {{{

[select]
border   = { fg = "blue" }
active   = { fg = "magenta", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "blue" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[completion]
border   = { fg = "blue" }
active   = { reversed = true }
inactive = {}

# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "blue" }
title   = {}
hovered = { fg = "magenta", underline = true }

# : }}}


# : Which {{{

[which]
cols            = 3
mask            = { bg = "black" }
cand            = { fg = "lightcyan" }
rest            = { fg = "darkgray" }
desc            = { fg = "lightmagenta" }
separator       = "  "
separator_style = { fg = "darkgray" }

# : }}}


# : Help {{{

[help]
on      = { fg = "black" }
run     = { fg = "magenta" }
desc    = { fg = "black" }
hovered = { reversed = true, bold = true }
footer  = { fg = "black", bg = "white" }

# : }}}


# : Notify {{{

[notify]
title_info  = { fg = "green" }
title_warn  = { fg = "yellow" }
title_error = { fg = "red" }

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "cyan" },

	# Media
	{ mime = "video/*", fg = "yellow" },
	{ mime = "audio/*", fg = "yellow" },

	# Archives
	{ mime = "application/zip",             fg = "magenta" },
	{ mime = "application/gzip",            fg = "magenta" },
	{ mime = "application/x-tar",           fg = "magenta" },
	{ mime = "application/x-bzip",          fg = "magenta" },
	{ mime = "application/x-bzip2",         fg = "magenta" },
	{ mime = "application/x-7z-compressed", fg = "magenta" },
	{ mime = "application/x-rar",           fg = "magenta" },
	{ mime = "application/xz",              fg = "magenta" },

	# Documents
	{ mime = "application/doc",   fg = "green" },
	{ mime = "application/pdf",   fg = "green" },
	{ mime = "application/rtf",   fg = "green" },
	{ mime = "application/vnd.*", fg = "green" },

	# Fallback
	# { name = "*", fg = "white" },
	{ name = "*/", fg = "blue" }
]

[icon]

rules = [
	# Programming
	{ name = "*.c"    , text = "", fg = "#3d59a1" },
	{ name = "*.cpp"  , text = "", fg = "#0db9d7" },
	{ name = "*.class", text = "", fg = "#db4b4b" },
	{ name = "*.cs"   , text = "󰌛", fg = "#9ece6a" },
	{ name = "*.css"  , text = "", fg = "#0db9d7" },
	{ name = "*.elm"  , text = "", fg = "#7aa2f7" },
	{ name = "*.fish" , text = "", fg = "#545c7e" },
	{ name = "*.go"   , text = "", fg = "#0db9d7" },
	{ name = "*.h"    , text = "", fg = "#bb9af7" },
	{ name = "*.hpp"  , text = "", fg = "#bb9af7" },
	{ name = "*.html" , text = "", fg = "#ff9e64" },
	{ name = "*.jar"  , text = "", fg = "#db4b4b" },
	{ name = "*.java" , text = "", fg = "#db4b4b" },
	{ name = "*.js"   , text = "", fg = "#F1F134" },
	{ name = "*.jsx"  , text = "", fg = "#2ac3de" },
	{ name = "*.lua"  , text = "", fg = "#0db9d7" },
	{ name = "*.nix"  , text = "", fg = "#737aa2" },
	{ name = "*.nu"   , text = ">", fg = "#73daca" },
	{ name = "*.php"  , text = "", fg = "#bb9af7" },
	{ name = "*.py"   , text = "", fg = "#ff9e64" },
	{ name = "*.rb"   , text = "", fg = "#f7768e" },
	{ name = "*.rs"   , text = "", fg = "#db4b4b" },
	{ name = "*.sbt"  , text = "", fg = "#545c7e" },
	{ name = "*.scala", text = "", fg = "#cc463e" },
	{ name = "*.scss" , text = "", fg = "#f55385" },
	{ name = "*.sh"   , text = "", fg = "#545c7e" },
	{ name = "*.swift", text = "", fg = "#e37933" },
	{ name = "*.ts"   , text = "", fg = "#0db9d7" },
	{ name = "*.tsx"  , text = "", fg = "#1354bf" },
	{ name = "*.vim"  , text = "", fg = "#73daca" },
	{ name = "*.vue"  , text = "󰡄", fg = "#73daca" },

	# Text
	{ name = "*.conf", text = "", fg = "#565f89" },
	{ name = "*.ini" , text = "", fg = "#565f89" },
	{ name = "*.json", text = "", fg = "#ff9e64" },
	{ name = "*.kdl" , text = "", fg = "#565f89" },
	{ name = "*.md"  , text = "", fg = "#c0caf5" },
	{ name = "*.toml", text = "", fg = "#c0caf5" },
	{ name = "*.txt" , text = "", fg = "#9ece6a" },
	{ name = "*.yaml", text = "", fg = "#565f89" },
	{ name = "*.yml" , text = "", fg = "#565f89" },

	# Archives
	{ name = "*.7z" , text = "" },
	{ name = "*.bz2", text = "" },
	{ name = "*.gz" , text = "" },
	{ name = "*.rar", text = "" },
	{ name = "*.tar", text = "" },
	{ name = "*.xz" , text = "" },
	{ name = "*.zip", text = "" },

	# Images
	{ name = "*.HEIC", text = "", fg = "#bb9af7" },
	{ name = "*.avif", text = "", fg = "#bb9af7" },
	{ name = "*.bmp" , text = "", fg = "#bb9af7" },
	{ name = "*.gif" , text = "", fg = "#bb9af7" },
	{ name = "*.ico" , text = "", fg = "#ff9e64" },
	{ name = "*.jpeg", text = "", fg = "#bb9af7" },
	{ name = "*.jpg" , text = "", fg = "#bb9af7" },
	{ name = "*.png" , text = "", fg = "#bb9af7" },
	{ name = "*.svg" , text = "", fg = "#FFB13B" },
	{ name = "*.webp", text = "", fg = "#bb9af7" },

	# Movies
	{ name = "*.avi" , text = "", fg = "#ff9e64" },
	{ name = "*.mkv" , text = "", fg = "#ff9e64" },
	{ name = "*.mov" , text = "", fg = "#ff9e64" },
	{ name = "*.mp4" , text = "", fg = "#ff9e64" },
	{ name = "*.webm", text = "", fg = "#ff9e64" },

	# Audio
	{ name = "*.aac" , text = "", fg = "#7dcfff" },
	{ name = "*.flac", text = "", fg = "#7dcfff" },
	{ name = "*.m4a" , text = "", fg = "#7dcfff" },
	{ name = "*.mp3" , text = "", fg = "#7dcfff" },
	{ name = "*.ogg" , text = "", fg = "#7dcfff" },
	{ name = "*.wav" , text = "", fg = "#7dcfff" },

	# Documents
	{ name = "*.csv" , text = "", fg = "#9ece6a" },
	{ name = "*.doc" , text = "", fg = "#3d59a1" },
	{ name = "*.doct", text = "", fg = "#3d59a1" },
	{ name = "*.docx", text = "", fg = "#3d59a1" },
	{ name = "*.dot" , text = "", fg = "#3d59a1" },
	{ name = "*.ods" , text = "", fg = "#73daca" },
	{ name = "*.ots" , text = "", fg = "#73daca" },
	{ name = "*.pdf" , text = "", fg = "#db4b4b" },
	{ name = "*.pom" , text = "", fg = "#db4b4b" },
	{ name = "*.pot" , text = "", fg = "#ff9e64" },
	{ name = "*.potx", text = "", fg = "#ff9e64" },
	{ name = "*.ppm" , text = "", fg = "#bb9af7" },
	{ name = "*.ppmx", text = "", fg = "#ff9e64" },
	{ name = "*.pps" , text = "", fg = "#ff9e64" },
	{ name = "*.ppsx", text = "", fg = "#ff9e64" },
	{ name = "*.ppt" , text = "", fg = "#ff9e64" },
	{ name = "*.pptx", text = "", fg = "#ff9e64" },
	{ name = "*.xlc" , text = "", fg = "#73daca" },
	{ name = "*.xlm" , text = "", fg = "#73daca" },
	{ name = "*.xls" , text = "", fg = "#73daca" },
	{ name = "*.xlsm", text = "", fg = "#73daca" },
	{ name = "*.xlsx", text = "", fg = "#73daca" },
	{ name = "*.xlt" , text = "", fg = "#73daca" },

	# Lockfiles
	{ name = "*.lock", text = "", fg = "#737aa2" },

	# Misc
	{ name = "*.bin", text = "", fg = "#db4b4b" },
	{ name = "*.exe", text = "", fg = "#db4b4b" },
	{ name = "*.pkg", text = "", fg = "#db4b4b" },

	# Dotfiles
	{ name = ".DS_Store"     , text = "", fg = "#414868" },
	{ name = ".bashprofile"  , text = "", fg = "#9ece6a" },
	{ name = ".bashrc"       , text = "", fg = "#9ece6a" },
	{ name = ".gitattributes", text = "", fg = "#414868" },
	{ name = ".gitignore"    , text = "", fg = "#414868" },
	{ name = ".gitmodules"   , text = "", fg = "#414868" },
	{ name = ".vimrc"        , text = "", fg = "#73daca" },
	{ name = ".zprofile"     , text = "", fg = "#9ece6a" },
	{ name = ".zshenv"       , text = "", fg = "#9ece6a" },
	{ name = ".zshrc"        , text = "", fg = "#9ece6a" },

	# Named files
	{ name = "COPYING"      , text = "󰿃", fg = "#ff9e64" },
	{ name = "Containerfile", text = "󰡨", fg = "#3d59a1" },
	{ name = "Dockerfile"   , text = "󰡨", fg = "#3d59a1" },
	{ name = "LICENSE"      , text = "󰿃", fg = "#e0af68" },

	# Directories
	{ name = ".config/"    , text = "" },
	{ name = ".git/"       , text = "" },
	{ name = "Desktop/"    , text = "" },
	{ name = "Development/", text = "" },
	{ name = "Documents/"  , text = "" },
	{ name = "Downloads/"  , text = "" },
	{ name = "Library/"    , text = "" },
	{ name = "Movies/"     , text = "" },
	{ name = "Music/"      , text = "" },
	{ name = "Pictures/"   , text = "" },
	{ name = "Public/"     , text = "" },
	{ name = "Videos/"     , text = "" },

	# Default
	{ name = "*" , text = "" },
	{ name = "*/", text = "" },
]

# : }}}
