prSections:
  - title: My PRs
    filters: author:@me
    limit: 5

defaults:
  preview:
    open: false
    width: 80
  prsLimit: 20
  issuesLimit: 20
  view: repo
keybindings:
  prs: []
repoPaths: {}
pager:
  diff: delta
theme:
  colors:
    text:
      primary: "#E2E1ED"
      secondary: "#666CA6"
      inverted: "#242347"
      faint: "#b0b3bf"
      warning: "#F23D5C"
      success: "#3DF294"
    background:
      selected: "#1b1b33"
    border:
      primary: "#383B5B"
      secondary: "#39386B"
      faint: "#2B2B40"
