# yaml-language-server: $schema=https://dlvhdr.github.io/gh-dash/configuration/gh-dash/schema.json
prSections:
  - title: Mine
    filters: is:open author:@me -repo:microsoft/vscode
    layout:
      author:
        hidden: true
  - title: Review
    filters: is:open review-requested:@me
  - title: Developers
    filters: org:port-labs -author:@me is:open author:MPTG94 author:ozzs author:matanAlltra author:matanl490 author:pazhersh author:Eyal-Be author:Tomer-Buhadana-Port author:imran-port author:KeenBeast author:MatanPort
    layout:
      repo:
        width: 6
  - title: Port
    filters: org:port-labs
  - title: gh-dash
    filters: "is:open repo:dlvhdr/gh-dash"
  - title: Commented
    filters: commenter:@me
  - title: Subscribed
    filters: "\
      repo:nvim-telescope/telescope.nvim \
      repo:ldelossa/gh.nvim \
      repo:neovim/neovim \
      repo:withgraphite/graphite-cli \
      repo:cli/cli"
  - title: LSP
    filters: "-author:app/dependabot -author:app/github-action \
      repo:TypeFox/monaco-languageclient \
      repo:typescript-language-server/typescript-language-server \
      repo:CodinGame/monaco-vscode-api"
issuesSections:
  - title: Creator
    filters: author:@me
  - title: Commented
    filters: is:open commenter:@me
  - title: dlvhdr
    filters: org:dlvhdr
  - title: gh-dash
    filters: is:open repo:dlvhdr/gh-dash
  - title: Assigned
    filters: is:open assignee:@me

pager:
  diff: diffnav
defaults:
  view: repo
  refetchIntervalMinutes: 1
  layout:
    prs:
      repoName:
        grow: true,
        width: 10
        hidden: false
      base:
        hidden: true

  preview:
    open: true
    width: 70
  prsLimit: 20
  issuesLimit: 20
repoPaths:
  dlvhdr/gh-dash: ~/code/personal/gh-dash
  port-labs/*: ~/code/port/*

keybindings:
  universal:
    - key: g
      command: >
        cd {{.RepoPath}} && lazygit
  prs:
    - key: O
      builtin: checkout
    - key: C
      command: >
        tmux new-window -c {{.RepoPath}} '
        nvim -c ":silent Octo pr edit {{.PrNumber}}"
        '
    - key: b
      command: cd {{.RepoPath}} && gh pr view {{.PrNumber}} --json statusCheckRollup | command jq -rcj '.statusCheckRollup.[] | select(.context == "buildkite/mono") | .targetUrl' | xargs open
    - key: a
      command: >
        cd {{.RepoPath}} && git add -A && lazygit
    - key: v
      command: >
        gh pr review --repo {{.RepoName}} --approve --body "$(gum input --prompt='Approval Comment: ')" {{.PrNumber}}

theme:
  ui:
    sectionsShowCount: true
    table:
      compact: false
  colors:
    text:
      primary: "#E2E1ED"
      secondary: "#666CA6"
      inverted: "#242347"
      faint: "#B0B3BF"
      warning: "#E0AF68"
      success: "#3DF294"
    background:
      selected: "#1B1B33"
    border:
      primary: "#383B5B"
      secondary: "#39386B"
      faint: "#2B2B40"
