#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json
import = []

[[session]]
name = "home 🏠"
path = "~"

[[session]]
name = "code 💻"
path = "~/code"

[[session]]
name = "dotfiles ⚙️"
path = "~/dotfiles"
startup_command = "nvim"

[[session]]
name = "mono 💼"
path = "~/code/port/mono"

[[session]]
name = "gh-dash 🚀"
path = "~/code/personal/gh-dash"

[[session]]
name = "downloads 📂"
path = "~/Downloads"
startup_command = "e"

[[session]]
name = "late.sh 👾"
path = "~/"
