#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "Usage: $0 <title>"
    exit 1
fi

TITLE="$1"
git switch --create $(echo "$TITLE" | awk '{print tolower($0)}' | tr " " "-")

export JIRA_API_TOKEN=$(op read "op://Personal/Jira API Key/credential")
jira issue create -a dolevh@getport.io --type Task --summary ""$TITLE""
