#!/usr/local/bin/fish
# Translates program names to icons, so we an use them in our tmux config.
# Based on https://github.com/caarlos0/icons
# set tty $argv[1]
# set p (tty2process $tty)
set p $argv[1]
switch $p
	case ack fd find fzf grep rg atuin
		echo 
	case atop htop top
		echo 
	case bash fish zsh
		echo 
	case bat cat
		echo 
	case mprocs
		echo 
	case clx
		echo 
	case cp duplicate
		echo 
	case mv
		echo 󰉒
	case curl http pint lynx wget w3m
		echo 
	case docker docker-compose
		echo 
	case exa lf ls nnn ranger
		echo 󰙅
	case elixir mix
		echo 
	case gh gh-dash
		echo 
	case git lazygit tig
		echo 
	case glow
		echo 
	case go
		echo 
	case java mvn
		echo 
	case less more
		echo 
	case lua
		echo 
	case man
		echo 
	case nano pico
		echo 󰙏
  case node npm yarn
    echo 
	case nvim vim vi
		echo 
	case python pip
		echo 󰌠
	case rm
		echo 󰗨
	case rsync
		echo 
	case ruby irb
		echo 
	case scp ssh
		echo 󰌘
	case sleep
		echo 
	case spin
		echo 󰅀
	case sudo
		echo 
	case tail
		echo 󰅀
	case tmux
		echo 󰙀
	case youtube-dl
		echo 
  case slides
    echo 󰐩
  case '*'
    echo 
end
