#!/bin/sh

launchctl enable gui/501/com.paloaltonetworks.gp.pangpa
launchctl enable gui/501/com.paloaltonetworks.gp.pangps

sudo launchctl bootout gui/501 /Library/LaunchAgents/com.paloaltonetworks.gp.pangpa.plist
sudo launchctl bootstrap gui/501 /Library/LaunchAgents/com.paloaltonetworks.gp.pangpa.plist

sudo launchctl bootout gui/501 /Library/LaunchAgents/com.paloaltonetworks.gp.pangps.plist
sudo launchctl bootstrap gui/501 /Library/LaunchAgents/com.paloaltonetworks.gp.pangps.plist
