# LLA Configuration File

# Default sorting method for file listings
# Possible values: "name", "size", "date"
default_sort = "name"

# Whether to show icons by default
# When true, file and directory icons will be displayed in all views
# Default: false
show_icons = true

theme = "tokyo_night"

# Default format for displaying files
# Possible values: "default", "long", "tree", "grid"
default_format = "default"

# List of enabled plugins
enabled_plugins = []

# Directory where plugins are stored
plugins_dir = "/Users/dlvhdr/.config/lla/plugins"

# Maximum depth for recursive directory traversal
# Set to None for unlimited depth
default_depth = 3

[sort]
# List directories before files
# Default: false
dirs_first = true

# Formatter-specific configurations
[formatters]

# Tree formatter configuration
[formatters.tree]
# Maximum number of entries to display in tree view
# Set to 0 to show all entries (may impact performance with large directories)
# Default: 20000
max_lines = 20000

# Lister-specific configurations
[listers]

# Recursive lister configuration
[listers.recursive]
# Maximum number of entries to display in recursive lister
# Set to 0 to show all entries (may impact performance with large directories)
# Default: 20000
max_entries = 20000

